export default {
  avatar_url: "https://avatars.githubusercontent.com/u/35306692?v=4",
  bio: "Front-end developer",
  blog: "",
  company: null,
  created_at: "2018-01-10T17:28:26Z",
  email: null,
  events_url: "https://api.github.com/users/dearvip0/events{/privacy}",
  followers: 1,
  followers_url: "https://api.github.com/users/dearvip0/followers",
  following: 6,
  following_url: "https://api.github.com/users/dearvip0/following{/other_user}",
  gists_url: "https://api.github.com/users/dearvip0/gists{/gist_id}",
  gravatar_id: "",
  hireable: null,
  html_url: "https://github.com/dearvip0",
  id: 35306692,
  location: "Linh Trung Ward, Thu Duc District, Ho Chi Minh City.",
  login: "dearvip0",
  name: "Bao Thuong",
  node_id: "MDQ6VXNlcjM1MzA2Njky",
  organizations_url: "https://api.github.com/users/dearvip0/orgs",
  public_gists: 0,
  public_repos: 57,
  received_events_url: "https://api.github.com/users/dearvip0/received_events",
  repos_url: "https://api.github.com/users/dearvip0/repos",
  site_admin: false,
  starred_url: "https://api.github.com/users/dearvip0/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dearvip0/subscriptions",
  twitter_username: null,
  type: "User",
  updated_at: "2022-05-02T08:25:47Z",
  url: "https://api.github.com/users/dearvip0",
};
